/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as Run from "@marko/run";


declare module "@marko/run" {
	interface AppData extends Run.DefineApp<{
		routes: {
			"/": { verb: "get"; meta: typeof import("../src/routes/+meta.json"); };
			"/api/auth/login": { verb: "post"; };
			"/api/auth/logout": { verb: "post"; };
			"/api/auth/register": { verb: "post"; };
			"/api/initiatives": { verb: "get" | "post"; };
			"/api/initiatives/[id]/join": { verb: "post"; };
			"/api/lang": { verb: "post"; };
			"/api/profile": { verb: ; };
			"/api/profile/password": { verb: "post"; };
			"/api/profile/skills": { verb: "post"; };
			"/api/profile/skills/[id]": { verb: ; };
			"/api/users": { verb: "get" | "post"; };
			"/api/users/[id]": { verb: ; };
			"/api/users/[id]/roles": { verb: ; };
			"/dashboard": { verb: "get"; meta: typeof import("../src/routes/dashboard/+meta.json"); };
			"/iniciatives": { verb: "get"; meta: typeof import("../src/routes/iniciatives/+meta.json"); };
			"/login": { verb: "get"; meta: typeof import("../src/routes/login/+meta.json"); };
			"/profile": { verb: "get"; meta: typeof import("../src/routes/profile/+meta.json"); };
			"/register": { verb: "get"; meta: typeof import("../src/routes/register/+meta.json"); };
			"/settings": { verb: "get"; meta: typeof import("../src/routes/settings/+meta.json"); };
			"/test": { verb: "get"; };
			"/users/create": { verb: "get"; meta: typeof import("../src/routes/users/create/+meta.json"); };
		}
	}> {}
}

declare module "../src/routes/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/auth/login/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/auth/login"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/auth/logout/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/auth/logout"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/auth/register/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/auth/register"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/initiatives/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/initiatives"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/initiatives/[id]/join/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/initiatives/[id]/join"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/lang/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/lang"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/profile/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/profile"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/profile/password/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/profile/password"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/profile/skills/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/profile/skills"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/profile/skills/[id]/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/profile/skills/[id]"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/users/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/users"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/users/[id]/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/users/[id]"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/api/users/[id]/roles/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/api/users/[id]/roles"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/dashboard/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/dashboard"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/iniciatives/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/iniciatives"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/login/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/login"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/profile/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/profile"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/register/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/register"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/settings/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/settings"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/users/create/+handler" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/users/create"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/dashboard/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/dashboard"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/iniciatives/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/iniciatives"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/login/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/login"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/profile/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/profile"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/register/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/register"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/settings/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/settings"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/test/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/test"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/users/create/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/users/create"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/+layout.marko" {
  export interface Input extends Run.LayoutInput<typeof import("../src/routes/+layout.marko")> {}
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/" | "/dashboard" | "/iniciatives" | "/login" | "/profile" | "/register" | "/settings" | "/test" | "/users/create"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}
